### ISSUE TITLE
Just wanted to say thank you for sharing!

### ISSUE THREAD

**Issue by evanheckert** [atsuyuki/dactyl-manuform-skeleton-edition-4x5#1]
I've had a skeleton variant of a dactyl manuform on my list of projects I'd like to tackle. I really appreciate you sharing your project! Can't wait to see its progress :)

**Comment by atsuyuki** [comment]
Thank you!
you can check realtime progress of my project on twitter 👉https://twitter.com/aaa_tu/status/1351311085035429888?s=21
