### ISSUE TITLE
OpenSCAD sources in the source?

### ISSUE THREAD

**Issue by dakipro** [atsuyuki/dactyl-manuform-skeleton-edition-4x5#3]
Hey and thanks for sharing man. You mentioned that you have OpenScad files in the source, I am not able to find them, can you make sure they are uploaded?
I would like to add additional row of buttons and maybe customize something else as well
Thanks again!

**Comment by atsuyuki** [comment]
Thanks for letting me know, I realized my mistake and restored the scad data from the backup.

But be careful, this source is like a labyrinth.

https://github.com/atsuyuki/dactyl-manuform-skeleton-edition-4x5/tree/main/source/things
